# Generated by Django 4.2.13 on 2024-08-16 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPermissions',
            fields=[
                ('permissions', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.permission')),
            ],
            options={
                'permissions': (('add_staff', 'can add stuff user'), ('update_staff', 'Can edit stuff user'), ('view_staff', 'can view stuff users'), ('delete_staff', 'can delete stuff users')),
            },
        ),
    ]
